#!/usr/bin/env bash

VOLUME=/usr/src/app
USER=user
GROUP=user
VOLUME_UID=$(stat -c "%u" $VOLUME )
VOLUME_GID=$(stat -c "%g" $VOLUME )

if [ "$VOLUME_UID" != "0" ]
then
    getent group $VOLUME_GID
    [ $? -gt 0 ] && groupadd --gid $VOLUME_GID $GROUP
    getent passwd $VOLUME_UID
    [ $? -gt 0 ] && useradd --create-home --uid $VOLUME_UID --gid $VOLUME_GID $USER
else
    USER="root"
fi

COMMAND=${1:-cli}
shift 1

set -x

if [ "$COMMAND" == "cli" ]
then
    exec su $USER
else
    exec su $USER -c "/usr/local/bin/$COMMAND $(printf " %q" "$@")"
fi